import { ReduxProvider } from "~/ui/client";
import { Icon, NextLink } from "~/ui/server";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "../lib/myToast";
import TasksCounter from "./_components/TasksCounter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "task manager application",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Toaster position="bottom-center" />
				<ReduxProvider>
					<header className=" fixed top-0 left-0 w-full shadow">
						<nav className=" flex container justify-center  items-center p-4  ">
							<span className=" mr-auto capitalize text-3xl  font-bold ">
								logo
							</span>
							<ul className=" flex justify-center items-center gap-2 sm:gap-4   ">
								<li>
									<NextLink className=" text-sm px-2 py-1" href="/">
										home
									</NextLink>
								</li>
								<li>
									<NextLink className=" text-sm px-2 py-1  " href="/view-tasks">
										view tasks
									</NextLink>
								</li>
							</ul>
							<TasksCounter />
						</nav>
					</header>
					{children}
				</ReduxProvider>
			</body>
		</html>
	);
}
